### ISSUE TITLE
User email addresses not being exported

### ISSUE THREAD

**Issue by darrencrossley** [boboldehampsink/export#1]
Column is rendered in the csv but no data from craft is populated into it.

**Comment by boboldehampsink** [comment]
Sorry man, I have totally missed this issue... I can't reproduce it either, as it is exporting e-mailaddresses fine on my site. Do you have any specific settings that might cause this?

**Comment by darrencrossley** [comment]
Hey no worries,
So I can't really remember to be honest, I *think* I ended up basically taking your implementation and substituting exactly what fields I needed to export... in the end the project required me to do some more complex user grouping and cleanup on other user attributes before export so I needed to write a custom plugin.  Don't think there was anything strange about my config though which is why I filed the bug - would have been a few releases ago now though.
