### ISSUE TITLE
CSRF Issue

### ISSUE THREAD

**Issue by quinny233** [boboldehampsink/export#14]
I've added and installed the plugin fine, but when I try to access the exporter I get the error:

'Internal Server Error

The function "getCsrfInput" does not exist'

I've tried enabling 'enableCsrfProtection' => true in settings which did not fix the problem, so not too sure if there is anything else within Craft that the exporter is dependant on? Or reasons that may cause this?

**Comment by boboldehampsink** [comment]
You should update Craft
