### ISSUE TITLE
Downloaded filename issue.

### ISSUE THREAD

**Issue by lettie16** [boboldehampsink/export#21]
Hi

Have a strange issue with the file that is downloaded. When trying to open it in excel I get the following error:

The file format and extension of export.csv don't match The file could be corrupted or unsafe. When I proceed it tells me it is an SYLK file and can't be opened by excel.

Any ideas?

**Comment by boboldehampsink** [comment]
Hi,

Read this for explanation of the problem: https://support.microsoft.com/en-us/kb/323626

**Comment by lettie16** [comment]
Cheers Bob another Microsoft gliche!
