### ISSUE TITLE
Field being ignored

### ISSUE THREAD

**Issue by divan-moller** [boboldehampsink/export#25]
I have a Plain Text field as part of an entry that does not show in the Export Configuration. I have changed the Field Name, I have also recreated the field and cleared the cache.

What could cause a field to be omitted? The field is in use.

**Comment by boboldehampsink** [comment]
Try resetting the export map.

**Comment by divan-moller** [comment]
Thanks it did work, perhaps for usability it should be a button to reset the export map instead of the unobtrusive checkbox? Didn't even notice it.
