### ISSUE TITLE
Alternative separator

### ISSUE THREAD

**Issue by johnniefp** [boboldehampsink/export#26]
First off really handy plugin.

Would it be possible to change/choose the separator from a comma to something like a pipe?
Reason being I have commas in some of my category names which is causing an issue.

Thanks

**Comment by boboldehampsink** [comment]
Sure, you can use the hook `registerExportCsvDelimiter` to register pipes as delimiter. Alternatively, you can escape comma's with a backslash.

**Comment by johnniefp** [comment]
Thanks Bob!
