### ISSUE TITLE
Exporting Users with Checkboxes field is blank

### ISSUE THREAD

**Issue by stuartswan** [boboldehampsink/export#29]
I'm using Export to export a users list which is working great for all custom user fields except a custom field of type Checkboxes, column values are blank in resulting CSV although column heading is present. Seems to be supported from looking at the code?

**Comment by stuartswan** [comment]
Managed to fix this by removing the if is_array check from line 457 of services/ExportService.php

**Comment by boboldehampsink** [comment]
Can you submit a Pull Request for this?
