### ISSUE TITLE
"Entries" fields and "Users" fields are blank in the CSV export

### ISSUE THREAD

**Issue by thijskaspers** [boboldehampsink/export#3]
Somehow exporting "Entries" fields and "Users" fields are empty in our CSV exports. We need the entry Title for the Entry relation and the username or first/last name for the User relation.

Would be cool if the field mapper will let us choose which field of the related entry should be exported by the way.

-- Thijs

**Comment by boboldehampsink** [comment]
I'm really not able to reproduce it... could you mail me some server info perhaps? And could you submit your feature request in a new ticket?

**Comment by boboldehampsink** [comment]
I've been able to verify the problem and I'm working on a fix.

**Comment by boboldehampsink** [comment]
This is available now in the develop branch, and very soon in the master branch.

**Comment by thijskaspers** [comment]
Thanks!
