### ISSUE TITLE
Export Field list doesn't update after adding new fields to Entry Type

### ISSUE THREAD

**Issue by shanerobinson** [boboldehampsink/export#32]
Craft: 2.6.2944
Export: 0.5.10

Section Name: Products (Channel)
Entry Type(s): GenInfo, Notes

Field Group1: Summary, Description, Yadda0
Field Group2: Notes, Yadda1, Yadda2
Field Group3: MetaTitle, MetaDesc, MetaKeys

Initial Section->EntryType setup = Products->GenInfo
Fields = Group1

Initial Section->EntryType setup = Products->Notes
Fields = Group2

VERY FIRST EXPORT:
If I export Products->GenInfo->Ascending, all Group1 fields are available on "Choose which fields.." screen. All good. 

If I add Field Group2 to Products->GenInfo, then go through exact same Export as first export:
Products->GenInfo->Ascending - the Field Group2 fields do NOT display in "Choose which fields..." screen. 

If I change Export settings to Products->GenInfo->Descending - the Field Group2 fields DO display in "Choose which fields..." screen. 

If I change Export settings to Products->ALL->(Ascending|Descending) the Field Group2 fields DO display... 

From my extensive tests, it seems like the "Choose which fields..." screen is "caching" based on the first Export settings selected??? I've cleared cache, removed & added fields and field groups, removed and added data to fields, etc. 
No matter what I change in the Fields or Sections, the "Choose which fields..." screen doesn't update to reflect those changes. 

I see the _export_map.settings and _export_map.map values and can verify that the .map JSON "checked:" values DO update based on which fields I check for each Export test. 

I removed all the rows in _export_map, started a new Export with same settings as VERY FIRST EXPORT above and the Group2 fields DO display. 
Then ran through the full export, removed a field from the Products->GenInfo entry type and headed back to Exports... STILL shows in the "Choose which fields..." screen. 

RESULTS OF EXTENSIVE TESTING:
The list of available Export fields DOES NOT update when fields are added/removed from the Section's EntryType. UNLESS I empty the _export_map table.

**Comment by boboldehampsink** [comment]
Yes, that's what the "Reset export map" checkbox is for.

**Comment by shanerobinson** [comment]
Ugh... I feel incredibly stooooopid! 14 long days/night in a row working on migrating a huge EE site into Craft and I've gone partially blind to things like that?!?

Thank you so much for the amazing IMPORT and EXPORT plugins!!!

I'd love to "donate" or "buy you a beer" if you have something like that setup, or Paypal?

Thanks, Bob!
