### ISSUE TITLE
Export plugin takes down entire page...

### ISSUE THREAD

**Issue by nexflo** [boboldehampsink/export#35]
...while exporting.

Not so clever. I know its probably because PHP / Apache runs on one thread.....still....not good.
Maybe for that process into own process?

**Comment by boboldehampsink** [comment]
Yeah this is on my list. The export file should be built up in a task, then presented for download. Haven't had the time for it yet tho.

**Comment by nexflo** [comment]
Is this closed as it's fixed, or just closed?
