### ISSUE TITLE
Data dumps onto page and task hits timeout.

### ISSUE THREAD

**Issue by shawncothran** [boboldehampsink/export#38]
I am looking for some direction and I do see that the Todo’s in the readme include "Handle large exports more smoothly” which is my issue.

I have around 2k entries in a channel and when I try to export the entries, after a couple minutes of thinking about it, I get a dump of the comma delimited data and this error `Fatal error: Maximum execution time of 0 seconds exceeded in ...craft/app/models/BaseModel.php on line 282`
<--Not a ton of backend experience. I see line 282 is merging model attribute arrays, which I figure is the bulk of the work of plugin...

**Comment by boboldehampsink** [comment]
For now try exporting in batches
