### ISSUE TITLE
Exporting x entries / users

### ISSUE THREAD

**Issue by hubertprein** [boboldehampsink/export#4]
When testing the export on a lot of entries (10000 in our client scenario) the export will crash. Craft can't handle that much data and will give a memory exceeded message. Is there a chance you'll come up with a solution where the users is able export the data into several parts?

**Comment by boboldehampsink** [comment]
Yes, I'm working on offset/limit functionality

**Comment by hubertprein** [comment]
Great!

**Comment by boboldehampsink** [comment]
This is up for testing in the latest develop release. Would you mind giving me feedback?

**Comment by hubertprein** [comment]
Seems to work just fine.

However, when exporting 10000 entries and you decide to cut them down by 500 per export, one still has some work left to do. We have to fuse files together to make one proper import. Is there a way you'd create an automatic process for this? E.g.: Decide a limit upon start of export, and automatically add the offset and limited elements into a (already) created csv file, and just append to it.

How do you think about this?

**Comment by boboldehampsink** [comment]
I agree to have something like this, but it will be on the roadmap. I will release this current functionality to have atleast something to prevent crashes.
